# https://aka.ms/yaml

jobs:
- job: 'Travis'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
  variables:
    python.version: '3.6'
    gh.ref: github.com/jupyterlab/jupyterlab.git
  strategy:
    matrix:
      js:
        group: 'js'
      integrity:
        group: 'integrity'
      python:
        group: 'python'
      cli:
        group: 'cli'
        python.version: '3.5'
      docs:
        group: 'docs'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - bash: ./scripts/travis_install.sh
    displayName: 'install'
  - bash: ./scripts/travis_script.sh
    displayName: 'script'
  - bash: ./scripts/travis_after_success.sh
    displayName: 'after_success'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish pytest'