# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
- bash: sudo rm -rf $(which yarn)
  displayName: 'Remove yarn'

- bash: '! which yarn'
  displayName: 'Verify yarn removed'

- bash: mkdir ~/.jupyter
  displayName: 'Make .jupyter folder'

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'
- script: pip --version
  displayName: 'Show pip version'
- script: 'python -m pip install -e ".[test]"'
  displayName: 'Install python deps'
- script: jlpm versions
  displayName: 'Show JL version'
- script: jlpm config current
  displayName: 'Show JL config'
- script: jupyter serverextension enable --py jupyterlab
  displayName: 'Show JL server extension'

- script: python -c "from jupyterlab.commands import build_check; build_check()"
  displayName: 'Run build check'
- script: py.test --junitxml=junit/test-results.xml
  displayName: 'Run pytest'
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python'