# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
- bash: rm -rf $(which yarn)
- bash: '! which yarn'

- bash: mkdir ~/.jupyter

- script: python -m pip install --upgrade pip
- script: pip --version
- script: 'python -m pip install -e ".[test]"'
- script: jlpm versions
- script: jlpm config current
- script: jupyter serverextension enable --py jupyterlab

- script: python -c "from jupyterlab.commands import build_check; build_check()"
- script: py.test -v
