name: example-environment
channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy
  - matplotlib-base
  - nodejs=14
  - numpy
  - pip
  - python=3.8
  - tornado>=6.1
  - vega_datasets
  - xeus-python
