name: 'Pull Request Labeler'

# This workflow is triggered whenever a PR is opened, changed, or reopened.
on: [pull_request]

jobs:
  triage:
    name: Update PR Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
