name: 'Pull Request Labeler'


name: Pull Request Labeler
# This workflow is supposed to run every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  triage:
    name: Update PR Labels
    runs-on: ubuntu-latest
    steps:
      - uses: paulfantom/periodic-labeler@8c477b324178bda91aeede9a35ece2b8d8813478
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
